eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      defaultZone: http://localhost:8761/eureka
microservice:
  paymentService:
    endpoint:
      uri: http://PAYMENT-SERVICE/payment/doPayment
